# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-30 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Account_Balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
